### ISSUE TITLE
test results for alt_rtl8821ce

### ISSUE THREAD

**Issue by cemunal** [lwfinger/rtw88#100]
Hi,

I am testing alt_rtl8821ce on my hardware and I can say it works very stable then rtw88_8821ce module in kernel. No need to disable aspm or any kind of system freeze. ( tested on 5.19.13-1-MANJARO )

Thanks for new module, firstly :) and want to know how can I contribute as a last user. Attached my hardware details.
[lspci_vv_s.txt](https://github.com/lwfinger/rtw88/files/9745231/lspci_vv_s.txt)

**Comment by lwfinger** [comment]
You are welcome. There is no need to contribute anything.

Be aware that there is zero support for that alternative driver. If you have any problems, please do not post anything here. The driver is written by a different group at Realtek than the one that prepares the Linux kernel code. Even I do not have any access to the group that wrote it. My contact is with the official group. I asked if this driver existed, and if I could get a copy. I then tested to ensure that it built, and ran it briefly to verify that it worked for me, but I cannot vouch for it. When you upgrade to kernels 6.1 and newer, it will likely break. Good luck with the fixes.
