### ISSUE TITLE
Problem updating kernel to 6.0.0 or latest with RTL8723DE module

### ISSUE THREAD

**Issue by Noroxi** [lwfinger/rtw88#103]
I had 5.15 kernel, i installed the module with out problems, didn´t work so i think it was the kernel, so i update the kernel but when i retry the install i get stuck in here:
![Captura desde 2022-10-24 08-14-44](https://user-images.githubusercontent.com/22568330/197513652-ff77b9ca-5a2b-41b2-9336-019f670ede53.png)
Please help me, the module works before, but i don´t know when stops working after a reboot, so now i don´t have WIFI, bluetooth is working.
Kernel version: 6.0.3-060003-generic

**Comment by Noroxi** [comment]
Ok I solved the problem, i will show response of code
sudo make into rtw88 folder returns:
![Captura desde 2022-10-24 13-25-50](https://user-images.githubusercontent.com/22568330/197576990-caa7b688-1e1e-477c-af4b-c813917a2eab.png)
![Captura desde 2022-10-24 13-25-55](https://user-images.githubusercontent.com/22568330/197577001-ab93a326-c1b0-418a-b218-3c315a4264fb.png)
sudo make install returns:
![Captura desde 2022-10-24 13-27-21](https://user-images.githubusercontent.com/22568330/197577193-144f92d4-6cd8-48cd-8de8-89b246251ed5.png)
sudo modprobe rtw_8723de doesn´t returns anything, and wifi still not working, bluetooth is working but wifi isn´t.

**Comment by lwfinger** [comment]
The Bluetooth device is USB and the wifi device is PCI. They only inhabit the same chip, but they do not share a driver.

The command 'sudo modprobe rtw_8723de' ONLY responds with output if it is unable to load the module in question.

Please send the following outputs. I suppose that you will need to take a screen shot:
1. 'lspci -nn'
2. 'lsmod | grep rtw'

**Comment by Noroxi** [comment]
lspci -nn returns:
![Captura desde 2022-10-24 15-12-59](https://user-images.githubusercontent.com/22568330/197596425-bf2cc8c5-d493-44b8-9a51-6c244797a91c.png)
lsmod | grep rtw  I didn't have return to this comand

**Comment by lwfinger** [comment]
If 'lsmod | grep rtw' returned nothing, your modules are not loaded. Please do 'sudo modprobe -v rtw_8723de'.

Your 'lspci -nn' command shows that you have an RTW8723DE, thus the driver should have been loaded after reboot. With Kernel 5.15, there is a potential problem of the in-kernel driver interacting badly with drivers from this repo, but there is a possibility that everything is blacklisted.

**Comment by Noroxi** [comment]
`sudo modprobe -v rtw_8723de` returns:
![Captura desde 2022-10-24 15-56-36](https://user-images.githubusercontent.com/22568330/197604071-b6df4ad4-39e4-47c0-82e2-52bd666b8b76.png)
i will reboot

**Comment by Noroxi** [comment]
`sudo modprobe -v rtw_8723de` returns:
![Captura desde 2022-10-24 15-56-36](https://user-images.githubusercontent.com/22568330/197604537-728e41ca-030f-4937-83c0-071071f230cc.png)
after reboot nothing happened

**Comment by Noroxi** [comment]
i think that module is blacklisted. What do i need to do?
![Captura desde 2022-10-24 16-19-52](https://user-images.githubusercontent.com/22568330/197608165-2ff667d2-f72d-489c-ac45-e946ed624ed1.png)

**Comment by lwfinger** [comment]
Check rtl8723de.conf and rtw_8723de.conf. They should blacklist rtw88_8723de, but not rtw_8723de. The first one comes from the kernel.

After you did the 'sudo modprobe -v rtw88723de', did wifi work before you rebooted?

**Comment by Noroxi** [comment]
rtl8723de.conf i think it define antenna setting:
![Captura desde 2022-10-24 17-33-50](https://user-images.githubusercontent.com/22568330/197623784-654a5f63-9df6-4f02-8e85-c0fde6f8a58c.png)
same with rtw_8723de.conf
![Captura desde 2022-10-24 17-35-21](https://user-images.githubusercontent.com/22568330/197624218-4de3936b-a9cb-4f11-a4b0-1288146c38a9.png)
inside of blacklist-8723de.conf:

![Captura desde 2022-10-24 17-36-24](https://user-images.githubusercontent.com/22568330/197624400-0721882c-4231-4bbb-8607-3c3849241056.png)

**Comment by lwfinger** [comment]
You can delete rtl8723de.conf. That antenna setting is not used. Keep rtw_8723de.conf. Delete blacklist-8723de.conf.

**Comment by Noroxi** [comment]
I have to reboot after that?

**Comment by lwfinger** [comment]
Do you mean that it is still blacklisted?

Run the following command: 'sudo grep 8723 /etc/modprobe.d/*' and report the output.
Repeat for 'sudo grep 8723 /usr/lib/modprobe.d/*'

**Comment by Noroxi** [comment]
![Captura desde 2022-10-24 19-21-38](https://user-images.githubusercontent.com/22568330/197640927-11eb7e2e-b00f-4f3d-921a-318ff2453bc3.png)

**Comment by Noroxi** [comment]
Into every folder i check all the files, only find 8723 in the next files:
![Captura desde 2022-10-24 19-45-54](https://user-images.githubusercontent.com/22568330/197644038-b56107e5-230e-4f0d-84ba-837b16b8341a.png)

**Comment by lwfinger** [comment]
I have no idea why your system is blacklisting the files. You will need to 'sudo modprobe -v rtw_8723de' after every boot. Does wifi work after that?

**Comment by Noroxi** [comment]
Look this now:
![Captura desde 2022-10-25 15-47-50](https://user-images.githubusercontent.com/22568330/197858542-31316a8b-aaf2-42fd-8ab2-84f2581afac5.png)

**Comment by lwfinger** [comment]
Did you change kernels and forget to 'make' and 'sudo make install'? That has to be done every time that the kernel changes!!!!!!!!!

**Comment by Noroxi** [comment]
I didn't change the kernel! When i passed from 6 to 5 i installed again...

**Comment by Noroxi** [comment]
![Captura desde 2022-10-25 16-10-44](https://user-images.githubusercontent.com/22568330/197861214-4a00f352-0693-4d9c-8b32-6a4f9fca63aa.png)

**Comment by Noroxi** [comment]
Sorry, i did it, don´t work also. 
![Captura desde 2022-10-25 16-28-58](https://user-images.githubusercontent.com/22568330/197864621-52367493-d988-4a78-a86c-d54f05daa073.png)

**Comment by lwfinger** [comment]
That is probably not a failure. Use 'lsmod | grep rtw' to see if the modules are loaded.

If you do not have wifi, you will next need to check the output of the dmesg command to see if it has errors. That one will be too big for you to post photos.

**Comment by Noroxi** [comment]
I don't know exactly what i'm looking for, but:
![Captura desde 2022-10-26 11-21-21](https://user-images.githubusercontent.com/22568330/198052535-42042073-978a-4008-8276-fb2bd8ba0d80.png)
![Captura desde 2022-10-26 11-21-42](https://user-images.githubusercontent.com/22568330/198052552-ec0e0bca-da47-458b-9ca2-74d8e3a78382.png)
![Captura desde 2022-10-26 11-22-12](https://user-images.githubusercontent.com/22568330/198052578-beb6c65f-ba9c-40d3-8fb4-1faff400aeec.png)
![Captura desde 2022-10-26 11-23-03](https://user-images.githubusercontent.com/22568330/198052602-9efba185-5783-4fc7-a574-0454f5efb29d.png)

**Comment by lwfinger** [comment]
This driver does not know about the 'ant_sel' parameter. The file in /etc/modrobe.d/ that sets it can be deleted. Otherwise, I do not see any errors. It found the firmware. The fact that the driver was loaded at 4.6 seconds means that the device and driver are recognized, and not blacklisted.

Do the following:
sudo rfkill list
sudo modprobe -rv rtw_8723de
sudo modprobe -v rtw_8723de

Send the output of the first command, then the very end of the dmesg output.

**Comment by Noroxi** [comment]
![imagen](https://user-images.githubusercontent.com/22568330/198068710-35895140-f834-4ed6-b824-0ef15c7e70a3.png)
What do you mean with  the very end of the dmesg output?

**Comment by Noroxi** [comment]
I think that the problem is in core. Look at this:
![Captura desde 2022-10-26 12-31-48](https://user-images.githubusercontent.com/22568330/198070267-3a24e8b1-20f4-4193-91cc-22b22372ceed.png)
![Captura desde 2022-10-26 12-32-29](https://user-images.githubusercontent.com/22568330/198070280-5e543764-6561-44bd-948f-df4297f2bbb8.png)

**Comment by lwfinger** [comment]
Enter 'dmesg' command. When it finishes, that is the end.

**Comment by Noroxi** [comment]
![Captura desde 2022-10-26 12-49-25](https://user-images.githubusercontent.com/22568330/198074084-2191fabd-2a5f-44de-877a-f30ac3517b9e.png)

**Comment by lwfinger** [comment]
\I have no idea what you are unplugging and replugging to get those USB disconnects and reconnects, but they have nothing to do with rtw_8723de. There are no errors with it. The only thing missing is a rename of wlan0, but your system may not do that. It seems that the problem has to be with your user-space setup of a wireless device.

What does 'iw dev' show?

**Comment by Noroxi** [comment]
![Captura desde 2022-10-26 17-26-28](https://user-images.githubusercontent.com/22568330/198130635-556df8d7-c251-4e8c-b961-30c1b0ec0e4b.png)

**Comment by lwfinger** [comment]
If you do 'sudo iw dev wlan0 scan | egrep "signal|SSID', do you see output? Send me a picture.

**Comment by Noroxi** [comment]
![Captura desde 2022-10-26 17-53-41](https://user-images.githubusercontent.com/22568330/198135548-90310794-bcd3-4232-bbde-641e12f4d244.png)

**Comment by Noroxi** [comment]
Look this!!
![Captura desde 2022-10-26 18-00-55](https://user-images.githubusercontent.com/22568330/198136936-e110bec4-60de-4e33-932c-bdb697ff59bf.png)

**Comment by lwfinger** [comment]
Your software that controls the wifi has not enabled the device. That has nothing to do with this driver. As I do not know what distro you are using, I cannot help you with that. You will need to search for the method needed to bring up wifi on your setup.

From the code that I control, everything is working!

**Comment by Noroxi** [comment]
Ok thanks!
