### ISSUE TITLE
Make does not work on Fedora 36 kernel - 5.19.16-200.fc36.x86_64

### ISSUE THREAD

**Issue by Prashanith** [lwfinger/rtw88#104]
make -C /lib/modules/5.19.16-200.fc36.x86_64/build M=/home/dev007/rtw88 modules
make[1]: *** /lib/modules/5.19.16-200.fc36.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:84: all] Error 2

**Comment by lwfinger** [comment]
You have not installed the kernel-headers. The section of README.md has been updates.
