### ISSUE TITLE
Make fails on Kernel 6.0.7-301

### ISSUE THREAD

**Issue by triakshunn** [lwfinger/rtw88#105]
Hi!

I am trying to use this for RTL8822be.
I have installed the kernel-devel and kernel-header package. 

![image](https://user-images.githubusercontent.com/35093460/203306335-f470cb9c-5926-4173-82ba-39a41d508d70.png)
Now when I try `make` command in the rtw88 directory,I get the following error:

![image](https://user-images.githubusercontent.com/35093460/203306653-3f0c3ac5-f2c8-4094-aaaf-b439e8b0d5af.png)

I saw on other fedora forum [here](https://ask.fedoraproject.org/t/wifi-adapter-not-found-rtl8723de/4056/15) that its a kernel-devel and kernel-header dependency issue but here its showing that its installed,so idk whats the issue.
 Thanks!

**Comment by lwfinger** [comment]
I do not know. I created a new Fedora 37 virtual machine, updated it, and install kernel-headers and kernel-devel just as the README.md says for Fedora. After that, the necessary link in /lib/modules/$(uname -r)/build was there, and I could compile rtw88. My kernel is 6.0.9 after the update, but that should not make any difference.

**Comment by triakshunn** [comment]
Thanks for the reply!
Even I was able to build today! Idk what changed[I didnt do anything] but the build was successful. Anyways thanks for your time!

**Comment by triakshunn** [comment]
Thanks for the reply!
Even I was able to build today! Idk what changed[I didnt do anything] but the build was successful. Anyways thanks for your time!
