### ISSUE TITLE
Issue with rtw_8821ce

### ISSUE THREAD

**Issue by CSParadiso** [lwfinger/rtw88#106]
Hello everyone.
I've installed the last release of Ubuntu recently and cant fix an issue with this driver. Im not really sure is that is the problem neither.
I've followed the steps from this repository but the wifi keeps on failing sometimes.
I think that the screenshot shows that the driver is working but i dont know for sure (im learning).
If you have some advice, plis let me know.
Regards, Simon.
![image](https://user-images.githubusercontent.com/100451976/206295933-56401f96-6620-4635-aaba-973685fdd5ad.png)

**Comment by CSParadiso** [comment]
![image](https://user-images.githubusercontent.com/100451976/206296253-8a2d4775-11d2-47dc-8176-8e1aee5e489c.png)

**Comment by lwfinger** [comment]
Your screenshots show that you have an 8821ce and that the driver is loaded. Nothing more than that.

Does the output of dmesg contain any information about your wifi?

Does it show up in the output of 'iw dev'?

**Comment by lwfinger** [comment]
These outputs say it is working.

**Comment by CSParadiso** [comment]
Ok.
Thanks for the help. I will keep on trying, maybe there are some bad places for the Wifi signal.
Thanks again.

**Comment by CSParadiso** [comment]
Thank you very much @lwfinger. 
The best performance ive reach so far is:
signal: -48.00 dBm
I will keep on searching the best spot. Thanks again!

**Comment by lwfinger** [comment]
Anything larger than -60 should work. A signal of -48 dBm is nearly ideal. For various reasons, I run 4 different AP's at a distance of 1-2 m from my desk. The range of strengths ranges from -35 to -52 dBm.
