### ISSUE TITLE
rtl8822be cannot run normally

### ISSUE THREAD

**Issue by Raymond-du** [lwfinger/rtw88#11]
# uname -a

Linux Legion 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# sudo lshw -c network

*-generic DISABLED        
       description: Wireless interface
       product: Illegal Vendor ID
       vendor: Illegal Vendor ID
       physical id: 0
       bus info: pci@0000:07:00.0
       logical name: wlp7s0
       version: ff
       serial: 80:2b:f9:71:90:cb
       width: 32 bits
       clock: 66MHz
       capabilities: bus_master vga_palette cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtw_8822be driverversion=5.4.0-42-generic firmware=N/A latency=255 link=no maxlatency=255 mingnt=255 multicast=yes wireless=IEEE 802.11
       resources: irq:141 ioport:4000(size=256) memory:a4300000-a430ffff

# This is the result of dmesg | grep rtw

[  241.092855] WARNING: CPU: 1 PID: 296 at /home/raymond-du/文档/rtw88-master/pci.c:1171 rtw_dbi_read8.constprop.30+0xaa/0xc0 [rtw_pci]
[  241.092855] Modules linked in: ccm nls_iso8859_1 uvcvideo snd_sof_pci snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof_intel_byt videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 snd_sof_intel_ipc hid_multitouch snd_sof nvidia_uvm(OE) snd_sof_xtensa_dsp snd_hda_ext_core snd_soc_acpi_intel_match snd_hda_codec_realtek 8250_dw videobuf2_common snd_soc_acpi snd_hda_codec_generic ledtrig_audio mei_hdcp videodev intel_rapl_msr nvidia_drm(POE) mc nvidia_modeset(POE) snd_hda_codec_hdmi snd_soc_core snd_compress ac97_bus snd_pcm_dmaengine x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel nvidia(POE) snd_hda_intel snd_intel_dspcfg snd_hda_codec snd_hda_core rndis_host snd_hwdep snd_pcm cdc_ether snd_seq_midi snd_seq_midi_event i915 rtw_8822be(OE) rtw_8822b(OE) kvm rtw_pci(OE) crct10dif_pclmul rtw_core(OE) crc32_pclmul mac80211 snd_rawmidi usbnet ghash_clmulni_intel snd_seq aesni_intel cfg80211 ipmi_devintf mii snd_seq_device snd_timer crypto_simd ipmi_msghandler libarc4
[  241.092900] RIP: 0010:rtw_dbi_read8.constprop.30+0xaa/0xc0 [rtw_pci]
[  241.092908]  rtw_pci_link_ps+0x58/0xa0 [rtw_pci]
[  241.092912]  rtw_enter_ips+0x3c/0x50 [rtw_core]
[  241.092914]  rtw_ops_config+0xa2/0xf0 [rtw_core]
[  241.093003] rtw_8822be 0000:07:00.0: failed to read ASPM, ret=-5
[  241.093118] rtw_8822be 0000:07:00.0: stop vif 80:2b:f9:71:90:cb on port 0
[  243.291417] rtw_8822be 0000:07:00.0: failed to poll offset=0x5 mask=0x2 value=0x0
[  247.891002] rtw_8822be 0000:07:00.0: failed to poll offset=0x5 mask=0x2 value=0x0
[  247.891010] rtw_8822be 0000:07:00.0: mac power on failed
[  247.891011] rtw_8822be 0000:07:00.0: failed to power on mac
[  250.087721] rtw_8822be 0000:07:00.0: failed to poll offset=0x5 mask=0x2 value=0x0
[  250.087730] rtw_8822be 0000:07:00.0: mac power on failed
[  250.087731] rtw_8822be 0000:07:00.0: failed to power on mac

## can you help me with this issue ?

**Comment by lwfinger** [comment]
The warning comes from the statement "WARN(1, "failed to read DBI register, addr=0x%04x\n", addr);" The problem happened earlier, but you did not provide that log.

These are the kinds of issues that I cannot help you solve. Please read README.md and report the problem in the manner suggested there.
