### ISSUE TITLE
Error: While installing on EndeavourOS

### ISSUE THREAD

**Issue by ARBoyGo** [lwfinger/rtw88#114]
Follow up from [rtl8723du/#37](https://github.com/lwfinger/rtl8723du/issues/37)
You told me this is the right driver, 

<details>
<summary>Error Message</summary>

```
==> Leaving fakeroot environment.
==> Finished making: rtw89-dkms-git 1:r366.fce040c-1 (Sunday 05 February 2023 08:20:16 PM)
==> Installing package rtw89-dkms-git with pacman -U...
/usr/bin/makepkg: line 255: /usr/bin/sudo: Operation not permitted
==> WARNING: Failed to install built package(s).
```

</details>
This is the error, I'm facing.

**BTW, I got my BT supported, Even though it is not showing in lsusb**
<details>
<summary>This fixed it.</summary>

`sodo dmesg | grep -i bluetooth`

</details>

**Comment by lwfinger** [comment]
Do NOT try to install this driver with fakeroot. Follow the instructions in README.md. You must be logged in as root to install the driver.

That command that you used to "fix" your BT actually does nothing permanent. Using 'sudo dmesg' only reads the log information, and 'grep' selects some of the information.
