### ISSUE TITLE
rtl8821cu not work

### ISSUE THREAD

**Issue by zhangsd20** [lwfinger/rtw88#124]
log:

[   27.205315] rtw_8821cu 1-1.2:1.2: Firmware version 24.11.0, H2C version 12
[   27.444213] rtw_8821cu 1-1.2:1.2: rfe 38 isn't supported
[   27.467194] rtw_8821cu 1-1.2:1.2: failed to setup chip efuse info
[   27.473559] rtw_8821cu 1-1.2:1.2: failed to setup chip information
[   27.692940] usb 1-1.3: new full-speed USB device number 4 using ehci-platform
[   28.162941] usb 1-1.4: new full-speed USB device number 5 using ehci-platform

**Comment by lwfinger** [comment]
You need to report this on linux-wireless@vger.kernel.org. I have no idea what handling rfe 38 would entail.
