### ISSUE TITLE
Works perfectly on HP s15-eq1032ns!!

### ISSUE THREAD

**Issue by gbr000** [lwfinger/rtw88#125]
I'm just leaving this note I think it may be useful to others,

Notebook: [HP s15-eq1032ns](https://support.hp.com/us-en/document/c07043871)

```
sudo lshw -C network
*-network                 
       description: Wireless interface
       product: RTL8821CE 802.11ac PCIe Wireless Network Adapter
       vendor: Realtek Semiconductor Co., Ltd.
       physical id: 0
       bus info: pci@0000:02:00.0
       logical name: wlo1
       version: 00
       serial: XX:XX:XX:XX:XX:XX
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=rtw_8821ce driverversion=5.10.0-21-amd64 firmware=N/A ip=192.168.XX.XXX latency=0 link=yes multicast=yes wireless=IEEE 802.11
       resources: irq:53 ioport:f000(size=256) memory:fce00000-fce0ffff
```

```bash
uname -a
Linux user 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```

What I have tried so far: all other options in internet with no success!
Issues: I had to restart 3x times because a black screen pos reboot, but after that the wifi seems to work perfectly!
Note: Also it could be that I was just a bit precipitated and didn't allowed the proper reboot.
After: The wifi it's working perfectly, the signal is strong and it recognized all other networks, I still need to test the speed.

Thanks to the developer!

UPDATE: I tested the speed, in Windows I never could connect to 5ghz to my mobile hotspot. But in Linux I can!

I got solid 37Mbps later at 5Ghz compared to only 25Mbps in Windows at 2.4Ghz! The latency was a bit high and I'm not sure if it's normal, but the antenna of my provider is terrible anyway! (I got 1 stick of 4 antenna!)

```bash
#ookla-speedtest-1.2.0-linux-x86_64
Download:    25.95 Mbps [===================-] 99%   - latency: 1742.63    Download:    25.95 Mbps (data used: 42.6 MB)                                                   
                749.56 ms   (jitter: 93.05ms, low: 73.70ms, high: 2372.88ms
```

Another test:

```bash
Download:    38.42 Mbps (data used: 61.6 MB)                                                   
               2040.94 ms   (jitter: 95.95ms, low: 73.85ms, high: 3989.74ms
```

**Comment by jothi-prasath** [comment]
i am using the same wifi on [HP 14s-fq1030AU](https://support.hp.com/in-en/document/c07119618) 
the wifi works fine out of the box without any errors on both  archlinux/fedora 38 
i have some random disconnect issues in 2.4G but works perfectly in 5G which i mostly use
i have noticed that the wifi using more power #129 and that can be fixed by disabling the `SUPPORTS_DYNAMIC_PS`

**Comment by lwfinger** [comment]
The power issue should now be fixed in this repo, but not yet in the kernel version.
