### ISSUE TITLE
rtw8821ce more power usage

### ISSUE THREAD

**Issue by jothi-prasath** [lwfinger/rtw88#129]
when i was using kernel 5.19.13 the wifi power usage was avg 272 mW
now in kernel 6.2.8 the wifi power usage was 579 mW

**Comment by lwfinger** [comment]
A lot of features that give higher throuput have been enabled between 5.19 and 6.2. The code from this repo was unable to use them as the underlying kernel had no support.

Are you getting higher throuput?

**Comment by jothi-prasath** [comment]
This was 5.19.13 one
![image](https://user-images.githubusercontent.com/64248628/227607551-f31c73e7-9ee5-4a5b-a369-66e6068734a0.png)
This was 6.2.8 one
![image](https://user-images.githubusercontent.com/64248628/227607702-0473a478-fa13-4bf4-97fc-d4d45327ee75.png)

**Comment by lwfinger** [comment]
Run an iperf or speedest.net trial and tell me what the usage is under wifi load.

**Comment by jothi-prasath** [comment]
At the middle of the speedtest
![image](https://user-images.githubusercontent.com/64248628/227615778-efce1fe5-d637-48c4-817f-92c3d195037f.png)

after speedtest at idle
![image](https://user-images.githubusercontent.com/64248628/227616232-678e850d-19ae-45e2-b49b-48ef092f3b7f.png)

**Comment by jothi-prasath** [comment]
i found that this commit https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/net/mac80211/mlme.c?h=v6.3.3&id=28977e790b5d0e6d37db6e659cfbcde9d24ae718 is the culprit which introduces `SUPPORTS_DYNAMIC_PS` which disable powersave in rtw8821ce.

i revert this patch on kernel 6.3.4 and boom the power usage is low as desired.
![image](https://github.com/lwfinger/rtw88/assets/64248628/8472511e-7b27-41b9-be2e-da60be69462c)

**Comment by lwfinger** [comment]
Thanks for finding the cause of this issue. I have sent E-mail to make certain that the author of the patch looks at it again and verifies that it is what he intended. If so, then rtw88 is failing to inplement  SUPPORTS_DYNAMIC_PS correctly.

Once I hear from the author, then I will report back.

**Comment by lwfinger** [comment]
I just pushed a change that will disable SUPPORTS_DYNAMIC_PS while we find the bug in the drivers. With this change, you will not need to patch the kernel source unless you use the in-kernel driver.

**Comment by lwfinger** [comment]
The Realtek team announced that they are preparing patches for rtw88 and rtw89 to fix this problem. I will let you know when I merge those patches.

**Comment by lwfinger** [comment]
I just pushed Realtek's patch with SUPPORTS_DYNAMIC_PS turned on again. Please test with an unmodified kernel and let me know if it fixes your problem. Thanks.

**Comment by jothi-prasath** [comment]
yeah i installed on 6.3.4-arch1-1 and it fixed
