### ISSUE TITLE
rtw88 available in 5.8.0+ kernel

### ISSUE THREAD

**Issue by juliokarl** [lwfinger/rtw88#13]
Hi,

This might not be the correct place to ask, i try nonetheless.
the new Kernel 5.8.0+ from repo https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
has these drivers built in.
I compiled it as a module, i need 8821ce.
When loading the module, i get the following in syslog:

>Aug 10 10:53:34 localhost kernel: rtw_8821ce 0000:03:00.0: Firmware version 24.5.0, H2C version 12
>Aug 10 10:53:34 localhost kernel: rtw_8821ce 0000:03:00.0: rfe 2 isn't supported
>Aug 10 10:53:34 localhost kernel: rtw_8821ce 0000:03:00.0: failed to setup chip efuse info
>Aug 10 10:53:34 localhost kernel: rtw_8821ce 0000:03:00.0: failed to setup chip information

I have the correct firmware placed in
/lib/firmware/rtw88/rtw8821c_fw.bin

Any idea how to fix this?

Thank you!

**Comment by lwfinger** [comment]
Read the last paragraph from README.md. I know NOTHING of the internals of any of these chips/
