### ISSUE TITLE
Implicit declaration of function prandom_u32

### ISSUE THREAD

**Issue by colossus73** [lwfinger/rtw88#134]
Hello Larry, hope this message finds you well. I'm trying to compile the alt_rtl8821ce on a Debian not UBUNTU ;) 6.1 Kernel and I get this:

home/gt/rtw88/alt_rtl8821ce/os_dep/osdep_service.c: In function ‘rtw_random32’:
/home/gt/rtw88/alt_rtl8821ce/os_dep/osdep_service.c:2970:16: error: implicit declaration of function ‘prandom_u32’; did you mean ‘prandom_u32_max’? [-Werror=implicit-function-declaration]
 2970 |         return prandom_u32();
      |                ^~~~~~~~~~~
      |                prandom_u32_max

Could you please help? Is it just a matter of changing that call to prandom_u32_max()?

Many thanks

**Comment by lwfinger** [comment]
It was more than that. I pushed a set of fixes that will work through kernel 6.2.

The rtw88 drivers have been improved a lot in recent weeks. I would suggest that you try the main drivers and drop the alternate version. I know the build will break in kernel 6.3, and I'm not sure how soon I can fix it.
