### ISSUE TITLE
8723du disappears periodically

### ISSUE THREAD

**Issue by HeroesLament** [lwfinger/rtw88#142]
Hello Realtek team!

I see this message appearing in my kernel log buffer immediately after my NIC will disappear from my kernel:

[22029.551051] rtw_8723du 1-7:1.2: failed to get tx report from firmware

When I rmmod and modprobe the rtw_8723du module, it will come back for 10-30 minutes till it drops again.

Is there any way I can help debug this?

Thanks,

**Comment by lwfinger** [comment]
You completely misunderstand the point of this repo. It is not "The Realtek Team". I am one 83-year old guy that is good at fixing the kinds of problems that arise when building out-of-kernel modules. I am not an employee of Realtek, and I have no knowledge of the internal workings of the chips. As a result, I have no idea why the 8723du and the 8822cu generate this kind of error. My 8822bu works like a champ. As of this writing, it has been up for 55 hours without a single drop for any reason.

If you read file README.md, you will see what you should do for your kind of problem.

Before you post anything, read the thread on the 8822cu at https://marc.info/?l=linux-wireless&m=168381198132000&w=2 to see what kind of information you should provide. The "Realtek team" does read that list, but they will ignore any half-baked reports such as you posted above.
