### ISSUE TITLE
rtw_8723ds module produces error at start up

### ISSUE THREAD

**Issue by GiyoMoon** [lwfinger/rtw88#143]
Hey, since the last commit (fe8be699b43890431ff1c0fcaf1a48f75160f49c), the driver for the `RTL8723DS` chip doesn't work properly. I'm able to compile & install it, but when starting up, it produces errors. I've attached the dmesg log.

[dmesg.txt](https://github.com/lwfinger/rtw88/files/11545827/dmesg.txt)

**Comment by lwfinger** [comment]
I looked at the differences. Only 2 would be important on your chip. I pushed a test fix. Pull that and test. Thanks.
