### ISSUE TITLE
Poor performance on rtw_8821ce driver

### ISSUE THREAD

**Issue by a-h-ismail** [lwfinger/rtw88#149]
I installed the rtw88 driver from this repository and the WiFi performance is poor (barely 2mbps or less, and unstable connection).

The NIC detailed information:
```
03:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821CE 802.11ac PCIe Wireless Network Adapter
        DeviceName: WLAN
        Subsystem: Hewlett-Packard Company Device 831a
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin A routed to IRQ 137
        Region 0: I/O ports at 3000 [size=256]
        Region 2: Memory at a4200000 (64-bit, non-prefetchable) [size=64K]
        Capabilities: <access denied>
        Kernel driver in use: rtw_8821ce
        Kernel modules: rtw88_8821ce, rtw_8821ce
```

dmesg is filled with these entries
```
[  835.695925] rtw_8821ce 0000:03:00.0: timed out to flush queue 1
[  836.197920] rtw_8821ce 0000:03:00.0: timed out to flush queue 1
[  838.908002] rtw_8821ce 0000:03:00.0: timed out to flush queue 1
[  841.078223] rtw_8821ce 0000:03:00.0: timed out to flush pci tx ring[1]
[  841.494245] rtw_8821ce 0000:03:00.0: timed out to flush pci tx ring[1]
[  841.958173] rtw_8821ce 0000:03:00.0: timed out to flush pci tx ring[1]
[  844.974004] rtw_8821ce 0000:03:00.0: timed out to flush queue 1
[  845.452004] rtw_8821ce 0000:03:00.0: timed out to flush queue 1
[  845.908978] rtw_8821ce 0000:03:00.0: timed out to flush queue 1
```
My host is running Fedora 38 with kernel `6.3.5-200.fc38.x86_64`, I disabled `pcie_aspm` using the kernel command line but the issue persists.

Should be noted that the alt_rtl8821ce used to work perfectly until compilation broke for kernel 6.3

**Comment by lwfinger** [comment]
If you have kernel 6.3, what precautions did you take to avoid the kernel modules from interfering with this repo?

**Comment by a-h-ismail** [comment]
I have blacklisted rtw88_8821ce, as you can see in the output above the loaded module is `rtw_8821ce`.
This is my custom blacklist file if it helps:
```
cat /etc/modprobe.d/blacklist.conf 
blacklist rtw88_8821ce
blacklist uvcvideo
blacklist nouveau
options nouveau modeset=0
```

**Comment by lwfinger** [comment]
I fixed the build of alt_8871ce, but before you switch back to that driver, please add "disable_msi=y" to your rtw_pci options.

**Comment by a-h-ismail** [comment]
I gave this driver a last try with 'rtw_pci.disable_msi=y' added to the command line, but no difference was observed.
If I could help track down this issue with information from my device? I will provide all the necessary informations.

**Comment by a-h-ismail** [comment]
I switched back to the alt driver, working flawlessly. Thank you!

**Comment by lwfinger** [comment]
Thanks for trying. Your issue is likely with your BIOS, which has been an ongoing problem with both rtw88 and rtw89 drivers. There is nothing I can do about that, and likely nothing that Realtek can do.

Your only hope is that your laptop vendor upsates the BIOS and fixes the problem. As it appears to be necessary, I will keep the alt driver building.

**Comment by a-h-ismail** [comment]
> As it appears to be necessary, I will keep the alt driver building.
That would be greatly appreciated, thank you.

I checked the vendor page, there is an update to the BIOS that bumps the version a bit. HP makes updating the BIOS a hassle for Linux, so maybe later...

I'm curious why would the alt driver work but not the kernel/yours do?

**Comment by lwfinger** [comment]
The vendor driver (alt) expects a lot less from the PCI subsystem than does the rtw88 version. The Windows driver comes from the vendor driver, thus it behaves the same.
