### ISSUE TITLE
An error is given out , Dunno much .. Please help

### ISSUE THREAD

**Issue by achallion** [lwfinger/rtw88#16]
![image](https://user-images.githubusercontent.com/39681535/91757020-5ab6e900-ebeb-11ea-99b0-24147ced26c4.png)

It looks like a gcc error , I am not able to use wifi now
Thats so much of pain

**Comment by Lollixzc** [comment]
What command have you launched on the console? It seems that there is a command-line option that it is not understood, you should usually do `git clone repo` then `make` to compile all the files

**Comment by achallion** [comment]
![image](https://user-images.githubusercontent.com/39681535/91838687-87aae080-ec6b-11ea-928a-490472f2d71d.png)

It doesnt help also

**Comment by lwfinger** [comment]
Your system is completely screwed up. I have no idea where that extra command-line option is coming from. It is a Kali problem - ask them.

**Comment by achallion** [comment]
Ok 
Thank you
