### ISSUE TITLE
GWTC116-2: Connectivity fails after ~500MB of Download activity.

### ISSUE THREAD

**Issue by blackgamma7** [lwfinger/rtw88#173]
I have been using this driver on a GWTC116-2 that has been flashed with Linux Mint. I discovered an issue wherein after around 500-550 MB of downloading, with notable consistency, the connection would be unusable, with apt-get failing to connect to any of the mirrors during an upgrade.

**Comment by dubhater** [comment]
You forgot a few details, like which chip you have? What kernel version? What driver version? If I remember correctly, this problem was already fixed, so you probably don't have the latest version.

**Comment by blackgamma7** [comment]
Card: rtl_8723du Kernel: 5.15.0.89
though running inxi -Fxz showed the network as "No Device Data found".
I'm not sure how to pull up the exact driver version - I know I installed it some time in august and tried to "sudo make install" with the latest version since then.

**Comment by blackgamma7** [comment]
git log shows that it's the latest commit - Oct 24, 2023

**Comment by dubhater** [comment]
I guess the bug wasn't fixed after all.

There is another driver which may work better: https://github.com/lwfinger/rtl8723du

**Comment by blackgamma7** [comment]
Installed the "obselete" driver and so far, connection has been more reliable.
You mentioned the bug was supposedly fixed, could you tell me when and how that change was made?

**Comment by lwfinger** [comment]
Look at 'git log'. That will describe the changes.

**Comment by dubhater** [comment]
I was probably remembering this: https://lore.kernel.org/linux-wireless/20230210181946.cqnvxiomjv77xnf2@fatal.se/

**Comment by dubhater** [comment]
@blackgamma7  If you are still interested, try the latest commits from this repository. I think your problem is [fixed](https://github.com/lwfinger/rtw88/commit/4c77cee823053b789185f04e17547dfc0451d9a6).

**Comment by blackgamma7** [comment]
Tried out the update, still had the issue where the netowork would disconnect after <1GB of download.

**Comment by dubhater** [comment]
Can you double check what version of the driver is loaded with ``lsmod | grep rtw`` and ``git log``?

**Comment by blackgamma7** [comment]
I used repo commit 530df1a431313796351feaf9fd8350eef9fbbc93 (dated june 8th)
```
lsmod | grep rtw
rtw_8723du             16384  0
rtw_usb                24576  1 rtw_8723du
rtw_8723d              61440  1 rtw_8723du
rtw_8723x              24576  1 rtw_8723d
rtw_core              303104  3 rtw_8723d,rtw_usb,rtw_8723x
mac80211             1249280  2 rtw_usb,rtw_core
cfg80211              974848  3 rtw_core,8723du,mac80211
```
