### ISSUE TITLE
Decompression Failed with status 6 on kernel 6.7.9

### ISSUE THREAD

**Issue by Schoumi** [lwfinger/rtw88#189]
Hi,

After last kernel update on my laptop, I've build and install driver like before, but module can't load.

The driver load and work perfectly fine with kernel: 6.6.15
```
lsmod | grep rtw
    rtw_8821ce             12288  0
    rtw_8821c              98304  1 rtw_8821ce
    rtw_pci                32768  1 rtw_8821ce
    rtw_core              303104  2 rtw_8821c,rtw_pci
    mac80211             1392640  2 rtw_core,rtw_pci
    cfg80211             1343488  2 rtw_core,mac80211
```

My disto is: devuan ceres (debian sid) and kernels are distro build, not custom

But when i try on kernel 6.7.9, I have an error:
```
modprobe rtw_8821ce
    modprobe: ERROR: could not insert 'rtw_8821ce': Invalid argument
```
When i look into dmesg, each time i try modprobe i have:
```
[  321.616319] decompression failed with status 6
```
modules can be found here for each installed kernel
```
find /lib/modules/ -iname "rtw_8821ce*"
    /lib/modules/6.7.9-amd64/kernel/drivers/net/wireless/realtek/rtw88/rtw_8821ce.ko.xz
    /lib/modules/6.6.15-amd64/kernel/drivers/net/wireless/realtek/rtw88/rtw_8821ce.ko.xz
```

Decompression with xz tool works perfectly fine but seems the kernel have a problem to do so.

when i look into kernels config differences I found this with other changes:
``` 
--- /boot/config-6.6.15-amd64	2024-02-04 21:28:21.000000000 +0100
+++ /boot/config-6.7.9-amd64	2024-03-13 12:13:41.000000000 +0100
CONFIG_MODULE_COMPRESS_XZ=y
 # CONFIG_MODULE_COMPRESS_ZSTD is not set
-# CONFIG_MODULE_DECOMPRESS is not set
+CONFIG_MODULE_DECOMPRESS=y
```

Any idea on how to resolve that?

**Comment by lwfinger** [comment]
Obviously, there is a bug in your kernel. I cannot fix that.

The best I can offer is to prevent the rtw88 build from compressing the modules. In Makefile, find the line that says "#Handle the compression option for modules in 3.18+", and delete it and the following 6 lines. The last one will be "#endif".

**Comment by Schoumi** [comment]
hum, it worked but it's odd since all other modules are working fine and compressed with xz too. So i dug up a bit.

I tried to check differences between modules I already have and the one build with this makefile: 
Every modules use CRC32 as integrity check but xz utility by default use CRC64 as integrity check and it seems the kernel doesn't support CRC64: https://docs.kernel.org/staging/xz.html?highlight=xz#notes-on-compression-options

I don't know what change between my two kernel, if it's the DECOMPRESS options or they enforce integrity check that was not done before but it's seems to be the problem.

So I change the Makefile to force CRC32 while compressing with xz and it work perfectly.

I change a bit too, the uninstall part (even if i have not change the modprobe -r that seems to don't reflect all the chipset module support by, as of today)

```diff
diff --git a/Makefile b/Makefile
index 852929a..8f07c2e 100644
--- a/Makefile
+++ b/Makefile
@@ -158,7 +158,7 @@ ifeq ($(COMPRESS_GZIP), y)
        @gzip -f $(MODDESTDIR)/*.ko
 endif
 ifeq ($(COMPRESS_XZ), y)
-       @xz -f $(MODDESTDIR)/*.ko
+       @xz -f -C crc32 $(MODDESTDIR)/*.ko
 endif
 
        depmod -a $(KVER)
@@ -174,7 +174,13 @@ uninstall:
        @modprobe -r rtw_8723de
        @modprobe -r rtw_8723de
        @modprobe -r rtw_8723de
+ifeq ($(COMPRESS_GZIP), y)
+       @rm -f $(MODDESTDIR)/rtw_*.ko.gz
+else ifeq ($(COMPRESS_XZ), y)
+       @rm -f $(MODDESTDIR)/rtw_*.ko.xz
+else
        @rm -f $(MODDESTDIR)/rtw_*.ko
+endif
        
        @depmod $(DEPMOD_ARGS)
        
```

**Comment by lwfinger** [comment]
Thanks for chasing this issue down. The difference between your two kernels is that the second turned comporession on. When it did, the Makefile detected this and compressed its modules appropriately.

I also added the zstd compression when the distro has modules with the .zst suffix, which mine actually does. That explains why I was not seeing the problem.

**Comment by Schoumi** [comment]
Hi, 

The problem was reintroduced during this merge: https://github.com/lwfinger/rtw88/commit/37e4b3c1a09698f3a804edc038fe0cf4ab28d6d9

The merge has override some change from the Makefile. CRC 32 for xz, zstd.

**Comment by dubhater** [comment]
I think I fixed it.
