### ISSUE TITLE
The commits from 37391d0 to 7528d5b improved 8822cu chipset stability a lot, thank you :-)

### ISSUE THREAD

**Issue by zfxsss** [lwfinger/rtw88#192]
Before those commits, the chipset would lose connection without clear reason (Even though, sometimes it could work properly for days).
The router signal strength fluctuates up and down. But now it works so stable, thanks a lot!

**Comment by lwfinger** [comment]
I wish I could take credit, but the patches were authored by others. My only contribution was to add them to this repo.

Glad to hear that they helped.
