### ISSUE TITLE
Integrate this backport in kernel sources using patch before building Kernel

### ISSUE THREAD

**Issue by petter1** [lwfinger/rtw88#201]
Is it possible to adapt this repo so that I can update the rtw88 in the kernel sources using a patch file? 

I have tried some ways, but the build has failed every time so far, most likely due to failures I made trying it...

**Comment by brianwitte** [comment]
Hi, if you are trying to get patches into the upstream kernel, you are going to want to pull from the tree shared here by the lead upstream maintainer:

https://lore.kernel.org/all/94c25902ef33433dbb582fc1c503704c@realtek.com/T/

This is out of scope for this repo as this code is modified to work with older kernel versions and does not reflect the in-tree source code accurately enough. 

Your patches would be a mess 😉
