### ISSUE TITLE
Will this repo support RTL8812AU?

### ISSUE THREAD

**Issue by Heyholiday067** [lwfinger/rtw88#217]
Hi,i read the supported devices in readme.md but i dont see the rtl8812au,will it be supported in future?

**Comment by dubhater** [comment]
It is supported even now. readme.md is a little outdated.

**Comment by morrownr** [comment]
@dubhater 

I have added RTW8812AU, RTW8821AU to the README.md.

FYI: As I have time, an going to update a few more things in the README.

**Comment by a5a5aa555oo** [comment]
I checked the devices ids in rtw88, it looks like RTL8723CS, RTL8811AU, RTL8811CU and RTL8812BU are also supported.

**Comment by morrownr** [comment]
@a5a5aa555oo 

I added all except RTL8723CS. Have you tried it?

**Comment by a5a5aa555oo** [comment]
Hi~ @morrownr 
No, I have no RTL8723CS to test, but the support for it was already in the linux mainline, the code here has support for it, too.
Please see: https://github.com/torvalds/linux/commit/64be03575f9e9772ebdebc7f067d533348602083

By the way, all the model names should be `RTL`8xxxx, not `RTW`8xxxxx. It would be great if you fix them when you have time, Thank you very much!
