### ISSUE TITLE
Issues with Realtek 8812au NIC and rtw88 Driver on Kali Linux VM

### ISSUE THREAD

**Issue by iamAika** [lwfinger/rtw88#221]
Hi good morning,
I am experiencing some issues with my VB Here are the details

VirtualBox Version: 7.0
Kali Linux Version: Kali GNU/Linux Rolling release 2024.2
NIC: Realtek 8812au
Kernel Version: 6.8.11-amd64
Driver used: 88XXau, /aircrack-ng/rtl8812au

Initial State:
I took a snapshot of the VM when Wi-Fi was working perfectly.
At that time, the lsmod command showed the driver 88XXau, and the Wi-Fi was operational.

Post-Reboot Problem:
After rebooting the VM, the Wi-Fi connection disappeared.
The ip show addr command no longer shows wlan0.
The lsmod command no longer lists the 88XXau driver.

Driver Replacement Attempt:
I attempted to switch to the rtw88 driver
I followed the instructions in the README.txt file, including blacklisting the 88XXau driver before installing rtw88.
The installation appeared to proceed correctly, but after rebooting, neither lsmod shows the new rtw88 driver nor does wlan0 appear.

During kernel update steps:

git pull (skipped due to no internet)
make (encountered errors)
sudo make install (same issues)

Error message during make:

make -C /lib/modules/6.8.11-amd64/build M=/root/rtw88 modules
make[1]: *** /lib/modules/6.8.11-amd64/build: No such file or directory.  Stop.
make: *** [Makefile:166: all] Error 2

How can I resolve the missing /lib/modules/6.8.11-amd64/build directory issue?
What steps can I take to ensure that the rtw88 driver is correctly installed and persists across reboots?

**Comment by a5a5aa555oo** [comment]
Before installing any out-of-tree driver, you have to install kernel headers first.
Use this command to install it and then try again.

`sudo apt install linux-headers-$(uname -r)`

**Comment by iamAika** [comment]
It said that everything was updated. I resolved it by just deleting the instance and starting over again from scratch. I followed the README.txt steps, and it works fine. I really appreciate your help anyway. If this teaches me anything, it's that when you take a snapshot, do it with the PC off.

Thx!
