### ISSUE TITLE
[RTW8821CE] Attempting to create RFMON interface with `active` flag causes interface to be stuck down.

### ISSUE THREAD

**Issue by c0des1ayr** [lwfinger/rtw88#236]
I'm using a laptop, and trying to make `wlan0mon` with the `active` flag makes it impossible to set the interface to up, making it useless for Open Wireless Link. Is it an issue due to back-porting, or just an upstream issue?

**Comment by dubhater** [comment]
rtw88 doesn't support active monitor mode. Maybe it could support that, but I haven't investigated yet. It depends on whether Realtek's firmware wants to cooperate or not.

**Comment by dubhater** [comment]
Oh, wait. In this repository rtw88 advertises support for active monitor mode. Larry did that for testing purposes, I guess, but it doesn't work.

**Comment by c0des1ayr** [comment]
I only made the issue because the module from this repo added `Device supports active monitor (which will ACK incoming frames)` to `iw phy`'s output, and I could create the interface with the flag.

**Comment by morrownr** [comment]
@c0des1ayr 

Your best bet for a WiFi 5 class adapter that supports `active monitor mode` is an adapter with a mt7610u or mt7612u chip. There are several listed in my Plug and Play List:

https://github.com/morrownr/USB-WiFi

@dubhater 

>  Larry did that for testing purposes, I guess, but it doesn't work.

It might be best if the false support is reverted. Do you want me to investigate?

FWIW: I have never seen AMM in any Realtek driver.

**Comment by dubhater** [comment]
@morrownr Sure, thanks!

**Comment by morrownr** [comment]
@dubhater 

> Sure, thanks!

Active Monitor Mode is gone. I think you were right, Larry was just trying to see if there was any code to support it.

**Comment by c0des1ayr** [comment]
Alright, I'll get an external WNIC instead.

**Comment by morrownr** [comment]
@c0des1ayr 

https://github.com/morrownr/USB-WiFi/blob/main/home/Recommended_Adapters_for_Kali_Linux.md

Any of the mt7612u and mt7610u based adapters should work fine. The one I have recommended the most to those using monitor mode and needing AMM is the Alfa ACHM. The ACM is really good also but does not quite have the range of the ACHM.

If you want something more modern the Edup adapter should work well but AMM appears to currently be broke in the driver. Hopefully that gets fixed.
