### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by bfree-github** [lwfinger/rtw88#25]
There doesn't seem to be a way to reach you, so I'm filing an issue :^)

I spent an entire day trying to get ubuntu to work with my realtek card, and after building about a dozen driver projects, I was about to give up.  Then I stumbled on a one-line mention of your rtw88 project and decided to give it a last try.

In just a couple of minutes I checked out your code, built it, and voila - everything works!  I wanted to thank you for creating/maintaining this lifesaver - you rock!

I consider this issue closed.

**Comment by aphelionz** [comment]
This was my experience as well setting up my laptop a few months back :) thank you!

**Comment by lwfinger** [comment]
You are both welcome.
