### ISSUE TITLE
Cross-Compile on latest revision show series of error message

### ISSUE THREAD

**Issue by briansune** [lwfinger/rtw88#256]
@dubhater 

After verified with old version and latest version on Kernel 5.4.0
It is confirmed that the repository led functions are introducing series of compile errors.

Please help and see any compatibility issue thank you.
I am enclosing some of the major errors here:

rtw88/main.c:2350:25: error: parameter 2 ('brightness') has incomplete type
 2350 |     enum led_brightness brightness)
rtw88/main.c:2349:12: error: function declaration isn't a prototype [-Werror=strict-prototypes]
 2349 | static int rtw_led_set_blocking(struct led_classdev *led,
 error: dereferencing pointer to incomplete type 'struct led_classdev'
  994 |  BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
kernel.h:994:51: error: 'struct rtw_dev' has no member named 'led_cdev'
  994 |  BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
rtw88/main.c:2354:29: error: passing argument 1 of 'rtwdev->chip->ops->led_set' from incompatible pointer type [-Werror=incompatible-pointer-types]
 2354 |  rtwdev->chip->ops->led_set(led, brightness);
      |                             ^~~
      |                             |
      |                             struct led_classdev *

rtw88/main.c:2354:34: error: type of formal parameter 2 is incomplete
 2354 |  rtwdev->chip->ops->led_set(led, brightness);

**Comment by dubhater** [comment]
Should be fixed by https://github.com/lwfinger/rtw88/commit/beee28a47d6e27ff2996e311852f6d480fcd8cfe.

**Comment by briansune** [comment]
@dubhater 

How about those C99 looks like it will also return error due to

>for(int i 

Seems like old C don't allow such syntax?

**Comment by briansune** [comment]
@dubhater 

After pull the repository I found there is a dependence issue related to

[#ifdef CONFIG_MAC80211_LEDS
	bool led_registered;
	char led_name[32];
	struct led_classdev led_cdev;
#endif](https://github.com/lwfinger/rtw88/blob/beee28a47d6e27ff2996e311852f6d480fcd8cfe/main.h#L2243-L2247)

It will return errors:

kernel.h:994:51: error: 'struct rtw_dev' has no member named 'led_cdev'
  994 |  BUILD_BUG_ON_MSG(!__same_type(*(ptr), ((type *)0)->member) && \
compiler_types.h:129:35: error: 'struct rtw_dev' has no member named 'led_cdev'
  129 | #define __compiler_offsetof(a, b) __builtin_offsetof(a, b)
main.c:2373:36: error: 'struct rtw_dev' has no member named 'led_cdev'
 2373 |  struct led_classdev *led = &rtwdev->led_cdev;
main.c:2384:17: error: 'struct rtw_dev' has no member named 'led_name'
 2384 |  snprintf(rtwdev->led_name, sizeof(rtwdev->led_name)

**Comment by dubhater** [comment]
Fixed now.

**Comment by briansune** [comment]
@dubhater 

Yes, tried linux kernel 5.4.0 and 6.1.0.
Both can compile properly.

Great Job~
