### ISSUE TITLE
Not working on new Linux kernel

### ISSUE THREAD

**Issue by halveen** [lwfinger/rtw88#26]
there's a new linux kernel 5.8.0-2parrot1-amd64 released recently but this drivers don't work with it'
the drivers worked well for me on kernel 5.7.0-2parrot2-amd64

**Comment by lwfinger** [comment]
What do you mean it does not work? Is there a build error, or is some error logged in the output of 'dmesg | less'? If the former, then you must do a git pull.

**Comment by halveen** [comment]
It does not show my WiFi driver at all, I just see Ethernet and vpn connection I tried reinstalling the drivers but that did not fix it
I will check what 'dmesg | less' output is.

**Comment by lwfinger** [comment]
ALWAYS do that dmesg check before you report an issue.

**Comment by halveen** [comment]
what should I check for when i run dmesg

**Comment by lwfinger** [comment]
Error messages!!!

**Comment by halveen** [comment]
I uninstalled the kernel, re-installing it now if I still have the problem I will let you know.
Thanks for your help

**Comment by halveen** [comment]
Uninstalled and re-installed the kernel problem solved, thank you.
