### ISSUE TITLE
[BUG] NEW DRIVER FOR RTL8814AU IS NOT WORKING

### ISSUE THREAD

**Issue by D357R0Y3R** [lwfinger/rtw88#267]
NEW DRIVER FOR RTL8814AU IS NOT WORKING. I HAVE TRIED USING THE LATEST COMMIT AND TRIED TO TEST THAT ON ARCH LINUX.

THE LAST COMMIT THAT CONTAINS DRIVER FOR RTL8814AU IS [Add firmware v33.6.0 for RTL8814AU](https://github.com/lwfinger/rtw88/commit/07ec7fc7c58c63106aba200ea7963094857f1e1a).

THE DRIVER IS LOCATED AT /usr/lib/firmware/rtw88/rtw8814a_fw.bin BUT IT SHOULD BE ZSTD COMPRESSED LIKE /usr/lib/firmware/rtw88/rtw8814a_fw.bin.zst.

HEY @morrownr, CAN YOU PLEASE TAKE A LOOK INTO THIS NEWLY ADDED DRIVER?

**Comment by a5a5aa555oo** [comment]
Currently 8814AU is not supported yet, please wait patiently.
