### ISSUE TITLE
RTL8822BU test report

### ISSUE THREAD

**Issue by briansune** [lwfinger/rtw88#275]
@dubhater 

When I load the driver there is a new error had printed which I never seen before

Failed with -71 <----

[ 7822.056178] rtw_8822bu 1-1:1.2: Firmware version 27.2.0, H2C version 13
[ 7822.671612] dwc2 f8180000.usb: Not connected
[ 7822.671640] dwc2 f8180000.usb: Not connected
[ 7822.671653] dwc2 f8180000.usb: Not connected
[ 7822.671677] rtw_8822bu 1-1:1.2: write register 0xc4 failed with -71
[ 7822.671694] dwc2 f8180000.usb: Not connected
[ 7822.672171] usbcore: registered new interface driver rtw_8822bu
[ 7822.688375] usb 1-1: USB disconnect, device number 7
[ 7823.268223] usb 1-1: new high-speed USB device number 8 using dwc2
[ 7823.476803] usb 1-1: New USB device found, idVendor=0bda, idProduct=b82c, bcdDevice= 2.10
[ 7823.476823] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 7823.476834] usb 1-1: Product: 802.11ac NIC
[ 7823.476842] usb 1-1: Manufacturer: Realtek
[ 7823.476850] usb 1-1: SerialNumber: 123456
[ 7823.479702] Bluetooth: hci0: RTL: examining hci_ver=07 hci_rev=000b lmp_ver=07 lmp_subver=8822
[ 7823.480705] Bluetooth: hci0: RTL: rom_version status=0 version=2
[ 7823.480723] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822b_fw.bin
[ 7823.480995] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822b_config.bin
[ 7823.481149] Bluetooth: hci0: RTL: cfg_sz 14, total sz 20270
[ 7823.485008] rtw_8822bu 1-1:1.2: Firmware version 27.2.0, H2C version 13
[ 7824.223669] Bluetooth: hci0: RTL: fw version 0xab6b705c
[ 7824.283987] Bluetooth: MGMT ver 1.22
[ 7829.141790] wlan0: authenticate with f8:6f:b0:0e:ae:e6
[ 7830.272697] wlan0: send auth to f8:6f:b0:0e:ae:e6 (try 1/3)
[ 7830.275303] wlan0: authenticated
[ 7830.280263] wlan0: associate with f8:6f:b0:0e:ae:e6 (try 1/3)
[ 7830.348607] wlan0: RX AssocResp from f8:6f:b0:0e:ae:e6 (capab=0x1011 status=0 aid=4)
[ 7830.380860] wlan0: associated
[ 7830.382577] wlan0: Limiting TX power to 35 (35 - 0) dBm as advertised by f8:6f:b0:0e:ae:e6
[ 7830.422469] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready

**Comment by dubhater** [comment]
It happens when the driver tries to switch the chip from USB 2 mode to USB 3 mode. The driver writes to a few hardware registers. The last write returns this error code but actually the write is successful.

I see the same thing with RTL8812AU and RTL8814AU. It's nothing to worry about.
