### ISSUE TITLE
RTL8811[A|C]U uses which driver to load and mount

### ISSUE THREAD

**Issue by briansune** [lwfinger/rtw88#278]
@dubhater @morrownr 

May I ask which driver is related to the 8811 series?
I am not sure which driver to insert and test.

**Comment by dubhater** [comment]
rtw_8821au for RTL8811AU

rtw_8821cu for RTL8811CU

**Comment by briansune** [comment]
@dubhater 

WIll try to load those drivers and make a test.
Thank you
