### ISSUE TITLE
Stopped working after 5.4.88-1-lts update

### ISSUE THREAD

**Issue by frog2077** [lwfinger/rtw88#36]
Not sure if its an issue on your the driver's or not. Had no issues during previous updates. After updating to 5.4.88-1-lts (on Arch) and reinstalling the drivers as usual, wifi went down. lspci and modprobe show module loaded correctly.
Steps taken: updated kernel, rebooted, reinstalled drivers, rebooted
Downgrading to 5.4.87-1-lts  solved the issue.

**Comment by lwfinger** [comment]
Sounds as if Arch or the kernel developers screwed up 5.4.88. I can only recommend that you stay with 5.4.87 and that it will be fixed in 5.4.89.
