### ISSUE TITLE
Miracast in 8821ce

### ISSUE THREAD

**Issue by grsm2020** [lwfinger/rtw88#38]
Hello, does 8821ce driver in this repo support miracast?

**Comment by lwfinger** [comment]
As I understand the situation, miracast in Linux requires extra sorftware. If that is present, the 8821ce should support the method.

**Comment by grsm2020** [comment]
Your driver is included to kernel?

**Comment by lwfinger** [comment]
It is not my driver - it comes from Realtek. It is not yet in the kernel, but it is in wireless-drivers-next, and should be included in kernel 5.12. This repo is a means of getting it into user's computers before it is fully incorporated.

**Comment by grsm2020** [comment]
As I know, but i can mistake that wext is not support of Miracast?
