### ISSUE TITLE
Make install fails in kali linux 2020.1b

### ISSUE THREAD

**Issue by easydush** [lwfinger/rtw88#41]
Dear Larry,
Some command aren't correct in your Makefile. I'd try to fix this problem and solved it correcting these steps:
```
diff --git a/Makefile b/Makefile
index 3fc1e79..6761829 100644
--- a/Makefile
+++ b/Makefile
@@ -104,7 +104,8 @@ endif
        @#copy firmware images to target folder
        @mkdir -p $(FIRMWAREDIR)/rtw88/
        @cp -f *.bin $(FIRMWAREDIR)/rtw88/
-       @mv $(FIRMWAREDIR)/rtw88/rtl8822cu_fw.bin $(FIRMWAREDIR)rtl_bt/.
+       @mkdir $(FIRMWAREDIR)rtl_bt/
+       @mv $(FIRMWAREDIR)rtw88/rtl8822cu_fw.bin $(FIRMWAREDIR)rtl_bt/.
        @echo "Install rtw88 SUCCESS"
```
 1. The directory `$(FIRMWAREDIR)rtl_bt/` doesn't exist.
 2. The path `$(FIRMWAREDIR)/rtw88/rtl8822cu_fw.bin` is jot correct.

Best wishes,
Izida.

**Comment by lwfinger** [comment]
I agree that there is a problem, but your fix was not quite right. If you do a 'git pull', you will get my new version.
