### ISSUE TITLE
How to remove

### ISSUE THREAD

**Issue by seamarhay** [lwfinger/rtw88#47]
Ran the make command for this and it worked like a charm. However, I then learned that I do not have this device. How do I remove the files once installed / made (make)?

**Comment by lwfinger** [comment]
Are you really that worried about a few MB of disk space? If you do not have the device, then those files are just like ALL the drivers for other devices you do not have. They just sit there on the disk. When you update your kernel and the old one is deleted, they will be gone.

Did you consider 'sudo make uninstall'?

**Comment by seamarhay** [comment]
Thanks for your help. I'm not worried about the MBs, soI'll just allow the
next kernel update delete the unused files. Just trying to keep the machine
clean. I did try the sudo make uninstall. Again thank you!

**Comment by castillofrancodamian** [comment]
> Are you really that worried about a few MB of disk space? If you do not have the device, then those files are just like ALL the drivers for other devices you do not have. They just sit there on the disk. When you update your kernel and the old one is deleted, they will be gone.
> 
> Did you consider 'sudo make uninstall'?

Using this command, I restarted the PC and I still see networks in network manager.
