### ISSUE TITLE
8723de Slow wifi speed, high ping and packet loss

### ISSUE THREAD

**Issue by antonysamuel** [lwfinger/rtw88#52]
in my hp laptop with rtl8723de chip WiFi speed is unstable and too slow. ping to modem is too high and also packet loss is there.
I'm getting full speed on windows and also via external WiFi adaptor. Tried manjaro , popOS, OpenSuse ,Garuda Linux with kernel 5.8 , 5.9 , 5.10 & 5.11 same issue is in all  WiFi worked otb in all distros but this issue exist.
I've installed this driver and same issue facing here too

Results of my actual WiFi speed and speed I'm getting is attached below.
Please do help me out to get it working.

![20210403_150622](https://user-images.githubusercontent.com/67637441/113497592-2ad61800-9523-11eb-8ff6-d35b72e347a2.jpg)
![20210403_115833](https://user-images.githubusercontent.com/67637441/113497594-2f023580-9523-11eb-93c3-6da795e0ec7b.jpg)
![20210403_150616](https://user-images.githubusercontent.com/67637441/113497595-3295bc80-9523-11eb-9334-3f1fd3c3244a.jpg)
![20210403_115958](https://user-images.githubusercontent.com/67637441/113497596-3590ad00-9523-11eb-9333-697e30b4039e.jpg)

**Comment by lwfinger** [comment]
As I have written many times, I am not the author of this driver, and I have no knowledge of the internals of any of the Realtek chips. My role is to provide the current, up to date, kernel source code for users of older kernels, and to fix build problems for older kernels. Any problems with stability and/or performance of the chips should be taken up with the actual authors, who can be reached using the procedure described in the last paragraph of README.md.

**Comment by munsoft004** [comment]
> in my hp laptop with rtl8723de chip WiFi speed is unstable and too slow. ping to modem is too high and also packet loss is there.
> I'm getting full speed on windows and also via external WiFi adaptor. Tried manjaro , popOS, OpenSuse ,Garuda Linux with kernel 5.8 , 5.9 , 5.10 & 5.11 same issue is in all WiFi worked otb in all distros but this issue exist.
> I've installed this driver and same issue facing here too
> 
> Results of my actual WiFi speed and speed I'm getting is attached below.
> Please do help me out to get it working.
> 
> ![20210403_150622](https://user-images.githubusercontent.com/67637441/113497592-2ad61800-9523-11eb-8ff6-d35b72e347a2.jpg)
> ![20210403_115833](https://user-images.githubusercontent.com/67637441/113497594-2f023580-9523-11eb-93c3-6da795e0ec7b.jpg)
> ![20210403_150616](https://user-images.githubusercontent.com/67637441/113497595-3295bc80-9523-11eb-9334-3f1fd3c3244a.jpg)
> ![20210403_115958](https://user-images.githubusercontent.com/67637441/113497596-3590ad00-9523-11eb-9333-697e30b4039e.jpg)

I also have identical issue on my HP laptop with `RTL8723DE`. Tried on Fedora and Arch Linux. On Arch tried both default and this git still can't find any fix.

OS: Arch Linux
Kernel: linux-5.12.5

**Comment by lwfinger** [comment]
I have no knowledge of the internals for any of the Realtek chips, thus my ability to fix problems with stability or performance are limited. My skills are such that I can fix build problems, and some things that issue BUG logs. The actual place to submit the stability and performance problems are outlined in the last paragraph of README.md.

There is an alternative driver available at https://github.com/smlinux/rtl8723de. Obviously, I do not control that repo, nor can I ensure that it will build on all kernels, but it might help you. That driver is derived from the same source as the Windows driver.
