### ISSUE TITLE
Is the vanilla kernel RL8723DE driver now the same code?

### ISSUE THREAD

**Issue by goverp** [lwfinger/rtw88#63]
Larry,does the 5.13 kernel's CONFIG_RTW88_RTL8723DE now build the same (maybe a little older) code for that wifi device - that's to say, can I now build directly from the kernel source rather than pulling your code and building an external module?

**Comment by lwfinger** [comment]
Yes, it is essentially the same code. The difference is that this repo contains any improvements that will be in 5.15. If the in-kernel version works for you, use it.
