### ISSUE TITLE
Wifi adapter not found

### ISSUE THREAD

**Issue by kishor1010** [lwfinger/rtw88#68]
I have tried everything but laptop is not recognising wifi driver. I tried to install the drivers but could not. Please help me !!!
![Screenshot from 2021-09-21 13-16-22](https://user-images.githubusercontent.com/91116958/134132491-75fbf6f4-6064-4a5e-af72-62ebc897c5e2.jpg)

**Comment by kishor1010** [comment]
![Uploading Screenshot from 2021-09-21 13-22-12.jpg…]()

**Comment by kishor1010** [comment]
![Uploading Screenshot from 2021-09-21 13-23-05.jpg…]()

**Comment by Lollixzc** [comment]
Have you read the readme? It seems that you don't have. Please at least say what model of card you have, but you don't need to open an issue if you cannot install the devices. Issues are made to report bugs on this repo, it seems you cannot install the driver so read the readme file first

**Comment by kelebek333** [comment]
Wrong driver, use this. https://github.com/lwfinger/rtw89

**Comment by lwfinger** [comment]
The last suggestion is correct. You need rtw89,. NOT rtw88.
