### ISSUE TITLE
sudo make error on rtw_8822be and 5.13.0-27-generic or higher kernel version.

### ISSUE THREAD

**Issue by davidto098** [lwfinger/rtw88#78]
When upgrading the kernel to versions equal to or higher than kernel 5.13.0-27-generic on ubuntu 20.04 LTS, I got this error when doing sudo make:

make -C /lib/modules/5.13.0-27-generic/build M=/home/david/rtw88 modules
make[1]: se entra en el directorio '/usr/src/linux-headers-5.13.0-27-generic'
  CC [M]  /home/david/rtw88/main.o
In file included from /home/david/rtw88/main.c:7:
/home/david/rtw88/main.h:34:93: error: missing binary operator before token "("
   34 | #if LINUX_VERSION_CODE < KERNEL_VERSION(5, 8, 0) && RHEL_RELEASE_CODE < RHEL_RELEASE_VERSION(8,0)
      |                                                                                             ^
make[2]: *** [scripts/Makefile.build:281: /home/david/rtw88/main.o] Error 1
make[1]: *** [Makefile:1879: /home/david/rtw88] Error 2
make[1]: se sale del directorio '/usr/src/linux-headers-5.13.0-27-generic'
make: *** [Makefile:80: all] Error 2

then i can´t do sudo make install.

**Comment by lwfinger** [comment]
That is now fixed.
