### ISSUE TITLE
Signing module

### ISSUE THREAD

**Issue by Kiriz01** [lwfinger/rtw88#80]
Hi. I have no idea how to sign the module, could you help me?

**Comment by lwfinger** [comment]
Use 'sudo make sign-install', but please look at README.md.

**Comment by shyamjos** [comment]
Do I need to run `sudo make sign-install` every time after kernel upgrade, or just `sudo make install` ?

PS: I have enabled secure boot

**Comment by lwfinger** [comment]
If you do a simple 'sudo make install', the module will not be signed, and will not load on a system with secure boot. You need to use 'sudo make install'.
