### ISSUE TITLE
RTL8822CU compatible

### ISSUE THREAD

**Issue by yibudak** [lwfinger/rtw88#81]
Can we use this repo for RTL8822CU ? There is a binary file named "rtl8822cu_fw.bin" but couldn't find any source code about 8822CU. Do all variations of 8822CX use the same driver?

**Comment by lwfinger** [comment]
No. This driver is for the PCI (RTL8822CE) version only. You can get the driver derived from the Realtek code used to generate the Windows, FreeBSD, and Linux USB driver for the CU from https://github.com/ulli-kroll/rtl8821cu. That repo says the same driver supports rtl8821cu and rtl8822cu.

My previous experience with the drivers derived from the Realtek USB drivers is that it will work, but will likely need modification for newer kernels, and that it will spam the logs.
