### ISSUE TITLE
[BUG] Broken networks redescovery

### ISSUE THREAD

**Issue by ComValer** [lwfinger/rtw88#88]
Hello. There's a bug that existed the entire time and wasn't fixed still.
The problem is next: The WiFi module properly discovers the networks Only once on The Boot. But then the listed networks will be lost if
- you connected to a single one and then switched to another one
- if AP was restarted (turn off, turn on) - wifi module won't see (list) it anymore.
Could you go look into this part of driver>? 😔😊

**Comment by lwfinger** [comment]
This kind of bug is beyond my capability to fix, which is why I wrote the last paragraph of README.md.
