### ISSUE TITLE
Confusion as to which driver I'm using.

### ISSUE THREAD

**Issue by arch-btw** [lwfinger/rtw88#9]
Hi,

First, let me thank you for your help, it is greatly appreciated.

I'm running into an issue and I'm not sure how to fix it, I have read the README several times now.

On your readme it says:

> The correct ones are:
> rtw_8723de rtw_8723d rtw_8822be rtw_8822b rtw_8822ce rtw_8822c rtw_core and rtw_pci

Is this sentence missing rtw_8821ce ?

When I do `lsmod | grep rtw` I get this:

> rtw_8821ce              0
> rtw_8821c             1 rtw_8821ce
> rtw_pci                  1 rtw_8821ce
> rtw_core                2 rtw_8821c,rtw_pci
> mac80211             2 rtw_core,rtw_pci
> cfg80211               3 rtw_core,mac80211,8821ce

I guess my questions is, how do I know if I'm using your driver, or the one from:

https://github.com/tomaspinho/rtl8821ce

Because I forgot which one I installed.

Is it possible that they have the same name?

And how do I switch between them if they have the same name?

I'm getting really weak wifi signal and don't know how to fix it.

Thank you so much!

**Comment by lwfinger** [comment]
Yes, I forgot the rtw_8821ce and rtw_8821c. I have no idea what thomaspinho names his/her drivers. Look for *.ko files in that directory.

I do not know how to fix yor weak signal either. As I carefully stated in README.md, take questions like that to the wireless-drivers mailing list. I am not am employee of Realtek. I have no knowledge of the internals of their chips.
