### ISSUE TITLE
Bluetooth fix for Debian GNU/Linux

### ISSUE THREAD

**Issue by EstebanMonge** [lwfinger/rtw88#96]
Hi team:

When you install this driver on Debian GNU/Linux probably you will an error that avoid to load the bluetooth firmware:

[    6.197650] Bluetooth: hci0: RTL: examining hci_ver=0a hci_rev=000c lmp_ver=0a lmp_subver=8822
[    6.198583] Bluetooth: hci0: RTL: rom_version status=0 version=3
[    6.198586] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cu_fw.bin
[    6.198606] bluetooth hci0: firmware: failed to load rtl_bt/rtl8822cu_fw.bin (-2)
[    6.198608] firmware_class: See https://wiki.debian.org/Firmware for information about missing firmware
[    6.198613] bluetooth hci0: firmware: failed to load rtl_bt/rtl8822cu_fw.bin (-2)
[    6.198614] bluetooth hci0: Direct firmware load for rtl_bt/rtl8822cu_fw.bin failed with error -2
[    6.198616] Bluetooth: hci0: RTL: firmware file rtl_bt/rtl8822cu_fw.bin not found

To fix that maybe you can include a symbolic link in the following way:
ln -s /lib/firmware/rtw88 /lib/firmware/rtl_bt

In my case I  avoided to install the firmware-realtek package.

Because the Debian package causes high CPU usages and some IRQ problem. The repo solved my problem with the commented modification.

**Comment by lwfinger** [comment]
Adding that link would break every other system with Bluetooth.

You should have added the firmware-bluetooth package, which is where the Realtek firmware resides.
